# Generated by Django 3.1.5 on 2021-01-20 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0005_auto_20210120_1944'),
        ('hyperlinks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hyperlink',
            name='child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.child'),
        ),
        migrations.AlterField(
            model_name='hyperlink',
            name='organ',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.organisator'),
        ),
        migrations.AlterField(
            model_name='hyperlink',
            name='teacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='organisations.teacher'),
        ),
    ]
