# Generated by Django 3.1.5 on 2021-01-07 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('organisations', '0002_auto_20210107_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
