# Generated by Django 3.1.5 on 2021-01-08 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisations', '0003_auto_20210107_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject_area',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
