# Generated by Django 3.1.5 on 2021-02-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='Type',
            field=models.CharField(default='line', max_length=150),
        ),
        migrations.AddField(
            model_name='task',
            name='autoCheckData',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='task',
            name='is_autoCheck',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='is_timing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.IntegerField(default=30),
        ),
    ]
