# Generated by Django 3.1.5 on 2021-01-13 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_auto_20210109_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='type',
        ),
        migrations.AddField(
            model_name='task',
            name='types',
            field=models.ManyToManyField(to='lessons.Type'),
        ),
    ]
