# Generated by Django 3.1.5 on 2021-01-13 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210113_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
