# Generated by Django 3.1.5 on 2021-02-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_auto_20210205_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Type',
            field=models.CharField(default='line', max_length=150),
        ),
    ]
