# Generated by Django 3.1.5 on 2021-01-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_answer_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
    ]
