# Generated by Django 3.1.5 on 2021-02-05 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_auto_20210205_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.tasktype'),
        ),
    ]
