# Generated by Django 3.1.5 on 2021-02-05 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_auto_20210205_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lessons.tests'),
        ),
    ]
