# Generated by Django 3.1.5 on 2021-01-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_auto_20210117_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='time_lesson',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
