# Generated by Django 3.1.5 on 2021-01-30 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_lesson_time_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='lesson',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson'),
        ),
    ]
