# Generated by Django 3.1.5 on 2021-02-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_auto_20210205_1857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='test',
        ),
        migrations.AddField(
            model_name='task',
            name='test',
            field=models.ManyToManyField(to='lessons.Tests'),
        ),
    ]
