# Generated by Django 3.1.5 on 2021-01-30 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_materials_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
