# Generated by Django 3.1.5 on 2021-02-10 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_auto_20210205_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='is_timing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tests',
            name='time_sec',
            field=models.IntegerField(default=300),
        ),
    ]
