# Generated by Django 3.1.5 on 2021-02-02 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_lesson_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='materials',
            name='Type',
            field=models.CharField(default='link', max_length=100),
        ),
        migrations.AddField(
            model_name='materials',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
